### ISSUE TITLE
OnSdkInitializedEvent not called when there is no internet

### ISSUE THREAD

**Issue by uchar** [AppLovin/AppLovin-MAX-Unity-Plugin#113]
Before updating to the latest version of Applovin SDK, `OnSdkInitializedEvent ` had been called even when there was no internet connection, but after the update, it doesn't fire anymore. I think it's important to fire this event all the time because It seems a breaking change to me, e.g in our game we rely on `sdkConfiguration.ConsentDialogState ` value and use it to show GDRP dialog if necessary

edit: It seems that it's not called when you are in development build too( android )

Adapters that I'm using : 

![image](https://user-images.githubusercontent.com/5172296/148052514-fbaeda87-2306-4d7b-8758-f977d338594d.png)
![image](https://user-images.githubusercontent.com/5172296/148052545-545e6e30-7a8b-456e-bb45-d3790b75f60b.png)

**Comment by thomasmso** [comment]
@uchar - Are you on Android or iOS?

**Comment by santoshbagadi** [comment]
Hi @uchar , we are not able to reproduce the issue locally with our latest AppLovin MAX plugin (v4.3.12) on both Android (v10.3.5) and iOS (v10.3.7).

Do you mind sharing the [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) when the issue is reproduced so we can further investigate.

**Comment by uchar** [comment]
@santoshbagadi @thomasmso  It's on Android

Here is the log :

```
D/AppLovinSdk(15121): [AppLovinSdk] 
D/AppLovinSdk(15121): ========================================
D/AppLovinSdk(15121): SDK Session Begin
D/AppLovinSdk(15121): ========================================
D/AppLovinSdk(15121): [PersistentPostbackManager] Deserializing 0 postback(s).
D/AppLovinSdk(15121): [PersistentPostbackManager] Successfully loaded postback queue with 0 postback(s).
D/AppLovinSdk(15121): [AppLovinCommunicator] Attached SDK instance: CoreSdk{sdkKey='6AQkyPv9b4u7yTtMH9PT40gXg00uJOTsmBOf7hDxa_-FnNZvt_qTLnJAiKeb5-2_T8GsI_dGQKKKrtwZTlCzAR', enabled=false, isFirstSession=false}...
D/AppLovinSdk(15121): [AppLovinSdk] Using identifier (9cc2906aafe3c1220c5eb2438cd10e9e) from previous session
D/AppLovinSdk(15121): [TaskManager] Scheduling TaskCollectAdvertisingId on ADVERTISING_INFO_COLLECTION queue in 0ms with new queue size 1
D/AppLovinSdk(15121): [TaskManager] Scheduling TaskRunnable on CACHING_OTHER queue in 0ms with new queue size 1
E/AppLovinSdk(15121): [AppLovinSdkSettings] Ignoring setting of verbose logging - it is configured from Android manifest already or AppLovinSdkSettings was initialized without a context.
I/AppLovinSdk(15121): [TaskManager] CACHING_OTHER queue finished task TaskRunnable with queue size 0
D/AppLovinSdk(15121): [AppLovinSdk] Initializing SDK for non-maiden launch
D/AppLovinSdk(15121): [TaskManager] Scheduling TaskFetchBasicSettings on MAIN queue in 0ms with new queue size 1
D/AppLovinSdk(15121): [AppLovinSdk] Setting plugin version: Max-Unity-4.3.12
D/AppLovinSdk(15121): [AppLovinSdk] Setting user id: 9cc2906aafe3c1220c5eb2438cd10e9e
I/AppLovinSdk(15121): [TaskManager] ADVERTISING_INFO_COLLECTION queue finished task TaskCollectAdvertisingId with queue size 0
D/AppLovinSdk(15121): [TaskManager] Scheduling TaskTimeoutFetchBasicSettings on TIMEOUT queue in 10250ms with new queue size 1
I/AppLovinSdk(15121): [ConnectionManager] Sending POST request to id=#1695016596 "https://ms.applovin.com/5.0/i?p=1%3A96943fdea087a1d759e08734fce0068af23ef96e%3AmBOf7hDxa_-FnNZvt_qTLnJAiKeb5-2_T8GsI_dGQKKKrtwZTlCzAR%3AzqaUWKT9631SZhZS21A7Vt7z-9fTvTV3yUFhnT0q3b9wioslJO68_8vgNSINjOJc"...
D/AppLovinSdk(15121): [ConnectionManager] Request to #1695016596 "ms.applovin.com/5.0/i" is 1:96943fdea087a1d759e08734fce0068af23ef96e:mBOf7hDxa_-FnNZvt_qTLnJAiKeb5-2_T8GsI_dGQKKKrtwZTlCzAR:zqaUWKT9631bLQEL0j0rAc_j9NmQqzZnmlx7mysv0qphgplXdv_gtYneI2hX0ulIt9HGIYq_9gQDWRL6MAsd5joetwrbpJ30PcwtmmAKhEHsnQxr0OUnDugOUYVJZ9yGpMHmkVuJSK5RHfqLyZcaapNLjVO4_LMnb3mVyx_QjOSs5MiagqT7lUGnWCTU5Z1gO0yJlYKjGjAtf4Bq__wbsAX51KYQmWqAajjqI0QeqHg_y14iWYqrNOz89pNcwoW2nrnuZKLE97hurL6nBYJTCYXGN1fy77EESyae2eRWz_M5tNzUmNjRzOG3rcQYbMc9KnAdVzaWmXJKx_bmOkzH_IwkD_9GODGnRIdIkXmfTA1QdB3aPU5HeK3bXRSpS6vKldEcthXh-LiIakYVdaRIWUfXrOXttugD2kX39O88S8bzEFU-h_VGlI9kyInDIIN7h0vZjpAhpU094nPuYajD7k1o2DDmkX3iuZ2DBhSKZg-EC5yr2g4zTjIoYQWL1WfZmL26Gcp40dtKYSMyDRaAT_CZ6C0u_rIfDUqDI22Lq-kya9IOQzZX-dchjnFwr1oQB-X5Zh0DWmJIZBsZPz4GzkAIYy7mlF2QeNNQ3sYn8CwBsGipNhn0UW3k8MlwtIm52ugKcPKybO7sZi54dVl_dTn5zpJUd7xqaqAoURKR_tJsFgxUq2sM9ZDGoZOn8YAqiE3TwMy80FZP6P51Gceozg-PeuqW9TmaKS50Yp8iQltI4vtRW87HByEnoV_8dCmHGX_eu2IvdMn-hiQey4ENA5FCrmP6EoQ-M8l1bZKdfOADCn3q62RdpdOnbweeaeY_r1fVmP1IglViHlQijj5AmcpJMr-VEi-itEKIow0lPSvxo3lstKe9WhSgbp99BgjT76wauNMCiZk0XCICRCwJPl8R4h6mLU0NsMZnLNF09fIy8GaI11yT1A3yd-Rqn0xDU5YY2b-FnkBcDC-D5HoIiMdDKkZkP6aVmMPvmnVBr2yOdJKUNVPBJCEg0tdEt6jzVwVmzwCum7yWdXasOtkufws1e3fVUmAaXlD_FuMv54Z3E2hTa1zUwFTty9XZ8TRGJ6GotR3Ei0geBz9vQpryij36LSHNK5O-O4Fg5_bCkBWSH1coq2GqUrqpO6JjpwbpT0C-32DX3rZ7eBX-SxQUQ2XjgXa_Tqs-iZylAZv3QZTa07JcnojD5xl3PFtPBx15QV9dVTy4iz-bJeQISFWQ6Z_I8SwjMuGyLWY8_UiFKXcvirHZhvAoHI0dXMathoGgngDhx1L0MZf0kYd9ewa2f9gLc9f7SuBPLGFgUvPlhPAE4aQukf_guWE4NwJEqOINOdyCvz9Dizbour9N16k76SwO4PXTPwTuh8Ru-TpyCwzBJWXDsVjAcgEo1bTWB8uA7LaHbc7Cg8SSr7Nj5YesJUqfBK77268W_BTuLILPLZqz3QSp-9nYp4X6qvmtt5hIRCHxp7aWGyhgrL8zj-kf7r_7lEhBr5roLZ4tDZv9WyzppYEGaCIYbV2iSAzlsOHbbIskgeP8f_QsohiRmrfjZxet8ymuQ84ZZXVW3pelcPPHxB-tvOB_-_2CCFhCOxFlrl93Bdyhjz9XjnUdbJJH6m2cyxTPjOLRYXzyJeTpZFloJwVlDH1mE9ZnP75EADyvjwhX3lpXZK_iYg7l6rr0IeBUi2JyeB4UJ9dRMBcXzJ_lwVm4wr-OhfcbCRAWZiJ0Q0-p4LeK3yp2Co5Nof7-tZ6s5_rLCKmKCIoaM8BpBl88QEecniR6QTq78_cDq8i4uWd7UtGOn8XYJVI-WhaCBICIC4tTLsIEcm5wsV92SLI-7HhAfLpg__M1TRYQVYNu4pfYqrU4YHBtcVgxrpA_66SFs5QHZKu7dkCJ8u54UWGMrab1Wd2XJh5ikhmwTjD5KDIzWuJZ6vupKQtjmMrhLCtCk2aC5ScmDaybFn2s0Z5N--AQf9zPh8Gac69yc2wshbJGN5PGazhZspkbWRr_hmVfUHIlBKCQahK2nx2oqjZIqaxuviZ6TtVC5iZ8rHT9-abrHfREyevtFQygC2FFXSMnwonGBd5VgUERN3Qec_BqT3Sq2jcozunDfswys89OSIKGrCcN3THJoC1AVEk_guX0YSDFwyTFKwIHdG2AaRy4eResEYT5LWsGC-eUcHDuX2-pMB3_DKxraWRbZyCQW0OpfI0iMzIUDT5fm-7Ns9nY0eBLbsYjxv6KCaVSnNU2_TvB1kwtFxJpIesIpeje_5KdQLC0rkbeRVqqbGmHnXIjpQfaGmf3E427-93ZR2rRSMTMhS8uc8fxOrewXHM0JQPu9XbSMgwZng1KvFCns_F6kb0M6ic-ickRsxhDKeloKgHmx_m9_Cfn7sc40a3ZjkD-Rbd459S_ep6voeL_FXay1zYAoGkLODgx-uB7pHC1MTMpW1tHFNwOcgSnEzmIHe_UYgGhNGYn2iPj8JGGi-YM5--xZQVRuC2UDSd9NT4cXfZMvq1yWEifZr61d9SPyNOcalQqJNnycHm5UQMGmHtcxAWsr-exIPVZkZBvCBLCqQZpgKXOtrFWBw5jSyPaKousBl5yoUUMsDiKb_3CZ9L52VBB76Lom75dn5EDTKwjwYGwwo1s83UN02sYlDKZw9YURpUPoLX9hWS1c0CvwnCwkk6RjoxqRfiLXlrVN-OdPJ18On4D5KUo4RsBsJrUIMVyLWCOQ1wb
E/AppLovinSdk(15121): [ConnectionManager] Failed POST returned -1009 in 0.022 s over unknown to #1695016596 "ms.applovin.com/5.0/i"
E/AppLovinSdk(15121): [TaskRepeatRequest] Unable to fetch basic SDK settings: server returned -1009
E/AppLovinSdk(15121): [TaskRepeatRequest] Task failed execution
E/AppLovinSdk(15121): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bytedance/sdk/openadsdk/TTAdSdk;
E/AppLovinSdk(15121): 	at com.applovin.mediation.adapters.ByteDanceMediationAdapter.getSdkVersion(ByteDanceMediationAdapter.java:231)
E/AppLovinSdk(15121): 	at com.applovin.impl.mediation.c.c.b(Unknown Source:45)
E/AppLovinSdk(15121): 	at com.applovin.impl.mediation.c.c.a(Unknown Source:23)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.g.a(Unknown Source:73)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.utils.g.a(Unknown Source:4)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.k$3.a(Unknown Source:27)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.e.h.a(Unknown Source:9)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.e.h.a(Unknown Source:0)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.e.h$1.a(Unknown Source:30)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.e.h$1.a(Unknown Source:2)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.e.t$1.a(Unknown Source:335)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.network.b.a(Unknown Source:1127)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.e.t.run(Unknown Source:101)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.e.o.a(Unknown Source:2)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.e.h.run(Unknown Source:222)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.e.o$c.run(Unknown Source:59)
E/AppLovinSdk(15121): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/AppLovinSdk(15121): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AppLovinSdk(15121): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/AppLovinSdk(15121): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AppLovinSdk(15121): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AppLovinSdk(15121): 	at java.lang.Thread.run(Thread.java:923)
E/AppLovinSdk(15121): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bytedance.sdk.openadsdk.TTAdSdk" on path: DexPathList[[zip file "/data/app/~~pAAvyh_CL5X9kmZYY46gJg==/com.dopamine.punchyrace3d-XDQSAHDYoY7wIKZrFed6Tw==/base.apk"],nativeLibraryDirectories=[/data/app/~~pAAvyh_CL5X9kmZYY46gJg==/com.dopamine.punchyrace3d-XDQSAHDYoY7wIKZrFed6Tw==/lib/arm, /data/app/~~pAAvyh_CL5X9kmZYY46gJg==/com.dopamine.punchyrace3d-XDQSAHDYoY7wIKZrFed6Tw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/system_ext/lib]]
E/AppLovinSdk(15121): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AppLovinSdk(15121): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AppLovinSdk(15121): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AppLovinSdk(15121): 	... 22 more
I/AppLovinSdk(15121): [TaskManager] MAIN queue finished task TaskFetchBasicSettings with queue size 0
E/AppLovinSdk(15121): [TaskTimeoutFetchBasicSettings] Timing out fetch basic settings...
E/AppLovinSdk(15121): [TaskTimeoutFetchBasicSettings] Task failed execution
E/AppLovinSdk(15121): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bytedance/sdk/openadsdk/TTAdSdk;
E/AppLovinSdk(15121): 	at com.applovin.mediation.adapters.ByteDanceMediationAdapter.getSdkVersion(ByteDanceMediationAdapter.java:231)
E/AppLovinSdk(15121): 	at com.applovin.impl.mediation.c.c.b(Unknown Source:45)
E/AppLovinSdk(15121): 	at com.applovin.impl.mediation.c.c.a(Unknown Source:23)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.g.a(Unknown Source:73)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.utils.g.a(Unknown Source:4)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.k$3.a(Unknown Source:27)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.e.h.a(Unknown Source:9)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.e.h.a(Unknown Source:0)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.e.h$b.run(Unknown Source:27)
E/AppLovinSdk(15121): 	at com.applovin.impl.sdk.e.o$c.run(Unknown Source:59)
E/AppLovinSdk(15121): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/AppLovinSdk(15121): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AppLovinSdk(15121): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/AppLovinSdk(15121): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AppLovinSdk(15121): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AppLovinSdk(15121): 	at java.lang.Thread.run(Thread.java:923)
E/AppLovinSdk(15121): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bytedance.sdk.openadsdk.TTAdSdk" on path: DexPathList[[zip file "/data/app/~~pAAvyh_CL5X9kmZYY46gJg==/com.dopamine.punchyrace3d-XDQSAHDYoY7wIKZrFed6Tw==/base.apk"],nativeLibraryDirectories=[/data/app/~~pAAvyh_CL5X9kmZYY46gJg==/com.dopamine.punchyrace3d-XDQSAHDYoY7wIKZrFed6Tw==/lib/arm, /data/app/~~pAAvyh_CL5X9kmZYY46gJg==/com.dopamine.punchyrace3d-XDQSAHDYoY7wIKZrFed6Tw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/system_ext/lib]]
E/AppLovinSdk(15121): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AppLovinSdk(15121): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AppLovinSdk(15121): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AppLovinSdk(15121): 	... 16 more
I/AppLovinSdk(15121): [TaskManager] TIMEOUT queue finished task TaskTimeoutFetchBasicSettings with queue size 0

```

**Comment by santoshbagadi** [comment]
@uchar , do you mind sharing the full logs as a gist or something (with timestamps). Also, could you see if you can reproduce the issue using our demo app?

It also looks like you are missing ByteDance adapter (although that shouldn't have be an issue for initialization).

**Comment by uchar** [comment]
@santoshbagadi I don't use ByteDance SDK
For using the Pangle adapter, Do I need to add it?

**Comment by santoshbagadi** [comment]
Yes, Pangle and ByteDance are the same and Pangle network requires the Bydance SDK and Adapter. If you added our adapter it [should automatically pull](https://repo.maven.apache.org/maven2/com/applovin/mediation/bytedance-adapter/4.1.1.6.0/bytedance-adapter-4.1.1.6.0.pom) the ByteDance/Pangle SDK as well. Do you mind sharing the `build.gradle` file (of `unityLibrary` on Unity 2019.3+) of the exported Android project.

**Comment by uchar** [comment]
@santoshbagadi  Sure 
```
// GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN

apply plugin: 'com.android.library'


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation(name: 'applovin-max-unity-plugin', ext:'aar')
    implementation(name: 'billing-3.0.3', ext:'aar')
    implementation(name: 'common', ext:'aar')
    implementation(name: 'facebook-android-wrapper-11.0.0', ext:'aar')
    implementation(name: 'mobmetricalib-3.21.1', ext:'aar')
    implementation(name: 'singular_sdk', ext:'aar')
    implementation project('FirebaseApp.androidlib')
    implementation project('MaxMediationGoogle.androidlib')
    implementation project('unity-android-resources')
}

android {
    compileSdkVersion 30
    buildToolsVersion '30.0.2'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 30
        ndk {
            abiFilters 
        }
        versionCode 2004007
        versionName '2.4.7'
        consumerProguardFiles 'proguard-unity.txt'
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.ress', '.resource', '.obb'] + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }

    packagingOptions {
        doNotStrip '*/armeabi-v7a/*.so'
        doNotStrip '*/arm64-v8a/*.so'
    }
}

def getSdkDir() {
    Properties local = new Properties()
    local.load(new FileInputStream("${rootDir}/local.properties"))
    return local.getProperty('sdk.dir')
}

def BuildIl2Cpp(String workingDir, String targetDirectory, String architecture, String abi, String configuration) {
    exec {
        commandLine(workingDir + "/src/main/Il2CppOutputProject/IL2CPP/build/deploy/netcoreapp3.1/il2cpp.exe",
            "--compile-cpp",
            "--libil2cpp-static",
            "--platform=Android",
            "--architecture=" + architecture,
            "--configuration=" + configuration,
            "--outputpath=" + workingDir + targetDirectory + abi + "/libil2cpp.so",
            "--cachedirectory=" + workingDir + "/build/il2cpp_"+ abi + "_" + configuration + "/il2cpp_cache",
            "--additional-include-directories=" + workingDir + "/src/main/Il2CppOutputProject/IL2CPP/external/bdwgc/include",
            "--additional-include-directories=" + workingDir + "/src/main/Il2CppOutputProject/IL2CPP/libil2cpp/include",
            "--tool-chain-path=" + android.ndkDirectory,
            "--map-file-parser=" + workingDir + "/src/main/Il2CppOutputProject/IL2CPP/MapFileParser/MapFileParser.exe",
            "--generatedcppdir=" + workingDir + "/src/main/Il2CppOutputProject/Source/il2cppOutput",
            "--baselib-directory=" + workingDir + "/src/main/jniStaticLibs/" + abi,
            "--dotnetprofile=unityaot")
        environment "ANDROID_SDK_ROOT", getSdkDir()
    }
    delete workingDir + targetDirectory + abi + "/libil2cpp.sym.so"
    ant.move(file: workingDir + targetDirectory + abi + "/libil2cpp.dbg.so", tofile: workingDir + "/symbols/" + abi + "/libil2cpp.so")
}

android {
    task BuildIl2CppTask {
        doLast {
              BuildIl2Cpp(projectDir.toString().replaceAll('\\\\', '/'), '/src/main/jniLibs/', 'ARMv7', 'armeabi-v7a', 'Release');
              BuildIl2Cpp(projectDir.toString().replaceAll('\\\\', '/'), '/src/main/jniLibs/', 'ARM64', 'arm64-v8a', 'Release');
        }
    }
    afterEvaluate {
        if (project(':unityLibrary').tasks.findByName('mergeDebugJniLibFolders'))
            project(':unityLibrary').mergeDebugJniLibFolders.dependsOn BuildIl2CppTask
        if (project(':unityLibrary').tasks.findByName('mergeReleaseJniLibFolders'))
            project(':unityLibrary').mergeReleaseJniLibFolders.dependsOn BuildIl2CppTask
    }
    sourceSets {
        main {
            jni.srcDirs = ["src/main/Il2CppOutputProject"]
        }
    }
}
```

**Comment by santoshbagadi** [comment]
Weird, I don't see the AL SDK or any of the adapter dependencies being added to the project at all. Do you mind running a `Force Resolve` on the `External Dependency Manager` by clicking `Assets -> External Dependency Manager -> Android Resolver -> Force Resolve` from the Unity menu.

**Comment by uchar** [comment]
@santoshbagadi  That's weird, it's working fine now. Thanks a lot  

It seems that the External dependency Manager has some issues because the "Enabled Resolution On Build" was checked and it should have to download them before build!
