### ISSUE TITLE
Adaptive Banner class not found issue 

### ISSUE THREAD

**Issue by ShahHusayn** [AppLovin/AppLovin-MAX-Unity-Plugin#128]
Target API: 31
Min API: 19
Unity Version: 2019.4.17f1
MAX Unity Plugin: AppLovin-MAX-Unity-Plugin-5.0.1-Android-11.0.0-iOS-11.0.0
Using Applovin & Unity Ads
I have disabled adaptive banner

`        MaxSdk.CreateBanner(bannerId, MaxSdkBase.BannerPosition.TopCenter);
MaxSdk.SetBannerExtraParameter(bannerId, "adaptive_banner", "false");
MaxSdk.SetBannerBackgroundColor(bannerId, new Color32(0,0,0,0));
`

Error Log I get:

`2022-01-28 19:45:01.275 4174-4174/? E/AppLovinSdk: [MediationUtils] Failed to get adaptive banner size. Will fallback to using format specific ad view ad size.
    java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.applovin.impl.mediation.c.c.a(Unknown Source:29)
        at com.applovin.mediation.MaxAdFormat.getAdaptiveSize(Unknown Source:14)
        at com.applovin.mediation.unity.MaxUnityAdManager$14.run(MaxUnityAdManager.java:1548)
        at android.app.Activity.runOnUiThread(Activity.java:7184)
        at com.applovin.mediation.unity.MaxUnityAdManager.positionAdView(MaxUnityAdManager.java:1485)
        at com.applovin.mediation.unity.MaxUnityAdManager.access$400(MaxUnityAdManager.java:67)
        at com.applovin.mediation.unity.MaxUnityAdManager$4.run(MaxUnityAdManager.java:1053)
        at com.applovin.mediation.unity.Utils$1.run(Utils.java:27)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8019)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at com.applovin.impl.mediation.c.c.a(Unknown Source:29) 
        at com.applovin.mediation.MaxAdFormat.getAdaptiveSize(Unknown Source:14) 
        at com.applovin.mediation.unity.MaxUnityAdManager$14.run(MaxUnityAdManager.java:1548) 
        at android.app.Activity.runOnUiThread(Activity.java:7184) 
        at com.applovin.mediation.unity.MaxUnityAdManager.positionAdView(MaxUnityAdManager.java:1485) 
        at com.applovin.mediation.unity.MaxUnityAdManager.access$400(MaxUnityAdManager.java:67) 
        at com.applovin.mediation.unity.MaxUnityAdManager$4.run(MaxUnityAdManager.java:1053) 
        at com.applovin.mediation.unity.Utils$1.run(Utils.java:27) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:8019) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) `

**Comment by chauduyphanvu** [comment]
@ShahHusayn, it seems like Google's AdMob SDK (hence `com.google.android.gms.ads.AdSize`) is not properly integrated into your project. 

Could you force dependency resolution or, if you use the manual Gradle template, share with us its content here? Make sure that the `com.google.android.gms.ads.AdSize` class and the `com.google.android.gms:play-services-ads` dependency exist.

Thanks.

Vu Chau
AppLovin Team

**Comment by ShahHusayn** [comment]
> 

@chauduyphanvu Thanks for quick response. I am not using Admob. I have only integrated Max_SDK in fresh project and installed UnityAds addon from Applovin integration tab. I have done forced dependency resolution. But when I run on device with android logcat connected I get this error. Its weird as I am not using any Google ads/packages. Also I am not using manual Gradle.

**Comment by chauduyphanvu** [comment]
@ShahHusayn, thanks for the info! Adaptive banner is a feature from AdMob / Google Ad Manager ([docs](https://dash.applovin.com/documentation/mediation/unity/getting-started/banners#adaptive-banners)), and since you are using AppLovin MAX Unity Plugin 4.3.1+, it is enabled by default (see the note on the same page).

So, if you are using adaptive banner, you will have to integrate the AdMob / Google Ad Manager adapters (using the [Integration Manager](https://dash.applovin.com/documentation/mediation/unity/mediation-adapters#integration-manager)). 

Otherwise, you can ignore that exception message. Let us know if you have any questions!

**Comment by ShahHusayn** [comment]
@chauduyphanvu Got it. I will ignore this exception for now and upload my app. I am just concerned about Google Playstore Android Vitals, I will test if it causes any issues once my build is live. Thanks for the quick reply.
