### ISSUE TITLE
Error inflating class com.applovin.mediation.ads.MaxAdView

### ISSUE THREAD

**Issue by surabhi6** [AppLovin/AppLovin-MAX-Unity-Plugin#224]
### MAX Plugin Version

11.7.0

### Unity Version

NA

### Device/Platform Info

Android

### Current Behavior

I am getting error in inflating banner ad for max. I am following this guide here https://dash.applovin.com/documentation/mediation/android/ad-formats/banners 

### How to Reproduce

    <com.applovin.mediation.ads.MaxAdView
        xmlns:maxads="https://schemas.applovin.com/android/1.0"
        android:id="@+id/bannerADView"
        android:layout_width="match_parent"
        android:layout_height="@dimen/_50sdp"
        app:layout_constraintBottom_toTopOf="@+id/frame_pic_frag"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>

bannerAdView = (MaxAdView) findViewById(R.id.bannerADView);
        bannerAdView.setPlacement(PlacementId.BANNER_ID);

**Comment by santoshbagadi** [comment]
Can you please send the full stacktrace along with the error message please so that we can further investigate the issue?

**Comment by surabhi6** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: lovely.flower.photo.frame, PID: 14177
    java.lang.RuntimeException: Unable to start activity ComponentInfo{lovely.flower.photo.frame/lovely.flower.photo.frame.MainActivity}: android.view.InflateException: Binary XML file line #14 in lovely.flower.photo.frame:layout/activity_main: Binary XML file line #24 in lovely.flower.photo.frame:layout/content_main: Error inflating class com.applovin.mediation.ads.MaxAdView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: android.view.InflateException: Binary XML file line #14 in lovely.flower.photo.frame:layout/activity_main: Binary XML file line #24 in lovely.flower.photo.frame:layout/content_main: Error inflating class com.applovin.mediation.ads.MaxAdView
     Caused by: android.view.InflateException: Binary XML file line #24 in lovely.flower.photo.frame:layout/content_main: Error inflating class com.applovin.mediation.ads.MaxAdView

Mainly this is the error message -  Error inflating class com.applovin.mediation.ads.MaxAdView

**Comment by surabhi6** [comment]
I upgraded gradle and it started working. Thanks!
