### ISSUE TITLE
Android InMobiMediationAdapter crash: "Caused by java.lang.IllegalStateException: Calling View methods on another thread than the UI thread."

### ISSUE THREAD

**Issue by Blackdiamond89** [AppLovin/AppLovin-MAX-Unity-Plugin#230]
### MAX Plugin Version

5.6.7

InMobi adapter version: android_10.1.3.1_ios_10.1.2.7

### Unity Version

2021.3.19f1

### Device/Platform Info

Redmi Note 10 JE, Android 12

### Current Behavior

Crash on start game:

Caused by java.lang.IllegalStateException: Calling View methods on another thread than the UI thread.
       at com.android.webview.chromium.WebViewChromium.b(chromium-TrichromeWebViewGoogle.aab-stable-541411733:12)
       at com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle.aab-stable-541411733:92)
       at android.webkit.WebView.<init>(WebView.java:443)
       at android.webkit.WebView.<init>(WebView.java:363)
       at android.webkit.WebView.<init>(WebView.java:345)
       at android.webkit.WebView.<init>(WebView.java:332)
       at android.webkit.WebView.<init>(WebView.java:322)
       at com.inmobi.media.kd.b(UnifiedSdk.java:80)
       at com.inmobi.sdk.InMobiSdk.init(InMobiSdk.java:289)
       at com.applovin.mediation.adapters.InMobiMediationAdapter.initialize(InMobiMediationAdapter.java:153)
       at com.applovin.impl.mediation.g$1.run(:109)
       at com.applovin.impl.mediation.g$11.run(:57)
       at com.applovin.impl.mediation.g.a(:19)
       at com.applovin.impl.mediation.g.a(:7)
       at com.applovin.impl.mediation.e.a(:103)
       at com.applovin.impl.mediation.e.a(:1)
       at com.applovin.impl.mediation.c.a$1.run(:63)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)

### How to Reproduce

Start game => crash

**Comment by thomasmso** [comment]
Hey @Blackdiamond89 - this issue is resolved in the v10.1.3.1 adapter - https://github.com/AppLovin/AppLovin-MAX-SDK-Android/commit/fb2fc9efd7a314f6cafe46d8fea447cf948b7a6b
