### ISSUE TITLE
Adcolony adapter crash

### ISSUE THREAD

**Issue by Blackdiamond89** [AppLovin/AppLovin-MAX-Unity-Plugin#234]
### MAX Plugin Version

5.8.0

### Unity Version

2021.3.19f1

### Device/Platform Info

Android 6.0.1, Nexus 5X

### Current Behavior

Crash when show Adcolony ads:
Adcolony adapter version: android_4.8.0.3_ios_4.9.0.0.3

`Caused by java.lang.ClassCastException: android.webkit.WebMessagePortWrapper cannot be cast to com.android.webview.chromium.WebMessagePortAdapter
       at com.android.webview.chromium.WebMessagePortAdapter.toAwMessagePorts(WebMessagePortAdapter.java:67)
       at com.android.webview.chromium.WebViewChromium.postMessageToMainFrame(WebViewChromium.java:1390)
       at android.webkit.WebView.postWebMessage(WebView.java:1880)
       at com.adcolony.sdk.c1.d(SourceFile:16)
       at com.adcolony.sdk.c1.c(SourceFile:2)
       at com.adcolony.sdk.c1$j.a(SourceFile:3)
       at com.adcolony.sdk.c1$e.safedk_c1$e_onPageFinished_711671e034f9c05f716f3e59632502f2(SourceFile:2)
       at com.adcolony.sdk.c1$e.onPageFinished(SourceFile)
       at com.adcolony.sdk.j$c.safedk_j$c_onPageFinished_df5925373c77328ce45a8c4c3c53804a(SourceFile:1)
       at com.adcolony.sdk.j$c.onPageFinished(SourceFile)
       at com.adcolony.sdk.l$c.safedk_l$c_onPageFinished_79020b79c988678f325604dbb19029ca(SourceFile:2)
       at com.adcolony.sdk.l$c.onPageFinished(SourceFile)
       at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:531)
       at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:188)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

### How to Reproduce

Show Adcolony ads

**Comment by santoshbagadi** [comment]
Hi @Blackdiamond89 ,  Based on the stacktrace, the error seems to be specific to AdColony SDK. Could you please reach out to the AdColony team regarding this error.
