### ISSUE TITLE
Attempt to invoke virtual method AppLovinSdk.getSettings() on a null object reference

### ISSUE THREAD

**Issue by rzer** [AppLovin/AppLovin-MAX-Unity-Plugin#316]
### MAX Plugin Version

6.1.1

### Unity Version

2021.3.22f1

### Device/Platform Info

Android

### Current Behavior

After updating AppLovinSDK from 11.1.1 to 12.1.0 i have got an error in Android builds:

```
2023.12.12 19:09:29.029 18083 18191 Debug AppLovinSdk [ConsentFlowSettings] Creating with initial values: isEnabled=true,
2023.12.12 19:09:29.029 18083 18191 Debug AppLovinSdk 	privacyPolicyUri=https://www.***.com/privacy-policy/,
2023.12.12 19:09:29.029 18083 18191 Debug AppLovinSdk 	termsOfServiceUri=null
2023.12.12 19:09:29.034 18083 18191 Error Unity AndroidJavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'com.applovin.sdk.AppLovinSdkSettings com.applovin.sdk.AppLovinSdk.getSettings()' on a null object reference
2023.12.12 19:09:29.034 18083 18191 Error Unity java.lang.NullPointerException: Attempt to invoke virtual method 'com.applovin.sdk.AppLovinSdkSettings com.applovin.sdk.AppLovinSdk.getSettings()' on a null object reference
2023.12.12 19:09:29.034 18083 18191 Error Unity 	at com.applovin.mediation.unity.MaxUnityPlugin.generateSdkSettings(MaxUnityPlugin.java:1398)
2023.12.12 19:09:29.034 18083 18191 Error Unity 	at com.applovin.mediation.unity.MaxUnityPlugin.initializeSdk(MaxUnityPlugin.java:98)
2023.12.12 19:09:29.034 18083 18191 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2023.12.12 19:09:29.034 18083 18191 Error Unity 	at com.unity3d.player.UnityPlayer.access$500(Unknown Source:0)
2023.12.12 19:09:29.034 18083 18191 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:126)
2023.12.12 19:09:29.034 18083 18191 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)
2023.12.12 19:09:29.034 18083 18191 Error Unity 	at android.os.Looper.loopOnce(Looper.java:210)
2023.12.12 19:09:29.034 18083 18191 Error Unity 	at android.os.Looper.loop(Looper.java:299)
2023.12.12 19:09:29.034 18083 18191 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2023.12.12 19:09:29.034 18083 18191 Error Unity   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <
```

So OnSdkInitializedEvent never called. Can you give some advice how can i fix it?

### How to Reproduce

1) Update from 5.11.1 -> 6.1.1 via Integration Manager
2) I don't import ExternalDependencyManager because i already have it in my manifest.json
3) I have custom path where Applovin Assets are stored. Some errors just after import, but then CMPService.cs file was moved automaticaly to right place and errors gone
4) Build apk and get error via Android Logcat

**Comment by JonathanLiuApp** [comment]
@rzer This happens when you call `SetMuted` before initializing the sdk. We are releasing a fix for this in our next release, but for now please call `SetMuted` after sdk initializing.

**Comment by rzer** [comment]
Thank you! It's worked
