### ISSUE TITLE
[MediationAdapterWrapper] Failed operation destroy for UNITY_NETWORK

### ISSUE THREAD

**Issue by binbinku** [AppLovin/AppLovin-MAX-Unity-Plugin#391]
### MAX Plugin Version

6.5.2

### Unity Version

2022.3.30f1

### Device/Platform Info

Google Pixel6A/Android13

### Current Behavior

`
[MediationAdapterWrapper] Failed operation destroy for UNITY_NETWORK
                                                                            org.koin.core.error.NoBeanDefFoundException: No definition found for type 'kotlinx.coroutines.CoroutineScope' and qualifier 'omid_scope'. Check your Modules configuration and add missing type and/or qualifier!
                                                                            	at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:301)
                                                                            	at org.koin.core.scope.Scope.resolveValue(Scope.kt:271)
                                                                            	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                            	at org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                            	at com.unity3d.services.UnityAdsSDK.finishOMIDSession(UnityAdsSDK.kt:202)
                                                                            	at com.unity3d.services.banners.BannerView.destroy(BannerView.java:86)
                                                                            	at com.applovin.mediation.adapters.UnityAdsMediationAdapter.onDestroy(UnityAdsMediationAdapter.java:122)
                                                                            	at com.applovin.impl.mediation.g.l(SourceFile:3)
                                                                            	at com.applovin.impl.mediation.g.$r8$lambda$M2XXF_uDkUJHBCb0aWTT2SbZ6RM(Unknown Source:0)
                                                                            	at com.applovin.impl.mediation.g$$ExternalSyntheticLambda0.run(Unknown Source:2)
                                                                            	at com.applovin.impl.mediation.g.a(SourceFile:5828)
                                                                            	at com.applovin.impl.mediation.g.$r8$lambda$8klZvVFxEvbeYtUWLTk7pAlNUX4(Unknown Source:0)
                                                                            	at com.applovin.impl.mediation.g$$ExternalSyntheticLambda9.run(Unknown Source:6)
                                                                            	at com.applovin.impl.mediation.g.a(SourceFile:5826)
                                                                            	at com.applovin.impl.mediation.g.b(SourceFile:578)
                                                                            	at com.applovin.impl.mediation.g.a(SourceFile:5774)
                                                                            	at com.applovin.impl.mediation.MediationServiceImpl.destroyAd(SourceFile:10)
                                                                            	at com.applovin.impl.mediation.ads.MaxAdViewImpl.e(SourceFile:24)
                                                                            	at com.applovin.impl.mediation.ads.MaxAdViewImpl.b(SourceFile:512)
                                                                            	at com.applovin.impl.mediation.ads.MaxAdViewImpl.$r8$lambda$Wau8Q-l6fA_RMw2m_C4sQ3qE2oA(Unknown Source:0)
                                                                            	at com.applovin.impl.mediation.ads.MaxAdViewImpl$$ExternalSyntheticLambda1.run(Unknown Source:4)
                                                                            	at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(SourceFile:4)
                                                                            	at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(SourceFile:1)
                                                                            	at com.applovin.impl.mediation.ads.MaxAdViewImpl.d(SourceFile:431)
                                                                            	at com.applovin.impl.mediation.ads.MaxAdViewImpl.a(SourceFile:54)
                                                                            	at com.applovin.impl.mediation.ads.MaxAdViewImpl$b.onAdLoaded(SourceFile:40)
                                                                            	at com.applovin.impl.mediation.ads.MaxAdViewImpl.a(SourceFile:1370)
                                                                            	at com.applovin.impl.mediation.ads.MaxAdViewImpl.a(SourceFile:1200)
                                                                            	at com.applovin.impl.mediation.ads.MaxAdViewImpl$d.onAdLoaded(SourceFile:10)
                                                                            	at com.applovin.impl.mediation.d$c.onAdLoaded(SourceFile:33)
                                                                            	at com.applovin.impl.bc.f(SourceFile:1735)
                                                                            	at com.applovin.impl.bc.$r8$lambda$e9-5sub6CNStsAwVYdM-WTE8a3o(Unknown Source:0)
                                                                            	at com.applovin.impl.bc$$ExternalSyntheticLambda20.run(Unknown Source:6)
                                                                            	at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(SourceFile:4)
                                                                            	at com.applovin.impl.bc.f(SourceFile:777)
                                                                            	at com.applovin.impl.bc.f(SourceFile:384)
                                                                            	at com.applovin.impl.wm.b(SourceFile:235)
                                                                            	at com.applovin.impl.wm.a(SourceFile:102)
                                                                            	at com.applovin.impl.wm$a$a.onAdLoaded(SourceFile:301)
                                                                            	at com.applovin.impl.bc.f(SourceFile:1735)
                                                                            	at com.applovin.impl.bc.$r8$lambda$e9-5sub6CNStsAwVYdM-WTE8a3o(Unknown Source:0)
                                                                            	at com.applovin.impl.bc$$ExternalSyntheticLambda20.run(Unknown Source:6)
                                                                            	at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(SourceFile:4)
                                                                            	at com.applovin.impl.bc.f(SourceFile:777)
                                                                            	at com.applovin.impl.bc.f(SourceFile:384)
                                                                            	at com.applovin.impl.mediation.MediationServiceImpl$b.f(SourceFile:5)
                                                                            	at com.applovin.impl.mediation.g$c.j(SourceFile:3)
                                                                            	at com.applovin.impl.mediation.g$c.$r8$lambda$8QFBzsAXz9jv17KlHNFUueM670I(Unknown Source:0)
                                                                            	at com.applovin.impl.mediation.g$c$$ExternalSyntheticLambda17.run(Unknown Source:4)
                                                                            	at com.applovin.impl.mediation.g$c.a(SourceFile:1254)
                                                                            	at com.applovin.impl.mediation.g$c.$r8$lambda$aniFfKvJoLE2scr2rX9lK823JEg(Unknown Source:0)
                                                                            	at com.applovin.impl.mediation.g$c$$ExternalSyntheticLambda9.run(Unknown Source:8)
                                                                            	at android.os.Handler.handleCallback(Handler.java:942)
                                                                            	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                            	at android.os.Looper.loopOnce(Looper.java:201)
                                                                            	at android.os.Looper.loop(Looper.java:288)
`

### Expected Behavior

no

### How to Reproduce

random

**Comment by binbinku** [comment]
Error print on BannerAd Refresh  (Unity Ads Medition)

**Comment by binbinku** [comment]
The AppLovinSdk throws this error every time a BannerAd is refreshed, occurring once with each refresh attempt.

**Comment by binbinku** [comment]
update unity ads mediation sdk
