### ISSUE TITLE
Error AndroidRuntime java.lang.NoSuchMethodError: No virtual method isIncentivized()Z in class Lcom/vungle/ads/internal/model/Placement; or its super classes (declaration of 'com.vungle.ads.internal.model.Placement' 

### ISSUE THREAD

**Issue by ctykaya** [AppLovin/AppLovin-MAX-Unity-Plugin#399]
### MAX Plugin Version

6.5.2

### Unity Version

2022.3.31f

### Device/Platform Info

Android

### Current Behavior

The app crashes with a NoSuchMethodError when attempting to load an ad using the AppLovin MAX SDK with Vungle mediation. The error occurs due to the absence of the isIncentivized() method in the Placement class of the Vungle SDK, causing the app to terminate unexpectedly.

### Expected Behavior

The app should successfully load and display ads using the AppLovin MAX SDK with Vungle mediation without crashing. The isIncentivized() method should be available in the Placement class, allowing the ad to be processed correctly.

### How to Reproduce

Cannot reproduce.

### Additional Info

Crash Log
```
2024/07/20 22:12:42.673 13059 13059 Debug AndroidRuntime Shutting down VM
0001/01/01 00:00:00.000 -1 -1 Info  --------- beginning of crash
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime FATAL EXCEPTION: main
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime Process: com.kayaon.cryptogames, PID: 13059
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime java.lang.NoSuchMethodError: No virtual method isIncentivized()Z in class Lcom/vungle/ads/internal/model/Placement; or its super classes (declaration of 'com.vungle.ads.internal.model.Placement' appears in /data/app/~~ZyqTakolBDtMETSj_x1oBw==/com.kayaon.cryptogames-kVn7lfvcMSaq8CTbZ60NRw==/base.apk!classes2.dex)
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime 	at com.fyber.fairbid.adtransparency.interceptors.vungle.VungleInterceptor.processAd(SourceFile:3)
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime 	at com.vungle.ads.internal.ui.VungleWebClient.safedk_VungleWebClient_onPageFinished_d298b859bb4101fde140002b07454561(Unknown Source:6)
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime 	at com.vungle.ads.internal.ui.VungleWebClient.onPageFinished(Unknown Source:12)
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime 	at WV.UY.b(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:12)
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime 	at WV.Z6.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:261)
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:106)
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime 	at android.os.Looper.loopOnce(Looper.java:210)
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:299)
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8319)
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
2024/07/20 22:12:42.679 13059 13059 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```

It crashes both banner, rewarded and Interstitial ads.

Environment
Unity Version: 2022.3.31f1
AppLovin MAX SDK Version: 12.5.0
Device: [e.g., Redmi Note 9 Pro]
Android Version: 12 (S - API 31)

We are also using CPX Research SDK  using web view implementation. Is it possible to conflict?

Mediation Platforms: 
Applovin
DT Exchange 
Inmobi 
Vungle

**Comment by richashukla23** [comment]
@ctykaya Could you please share the version of Vungle adapter you have installed?

**Comment by ctykaya** [comment]
Sure android_7.4.0.0_ios_7.4.00 the crash rate is %100. Cannot show any ad because of this crash

**Comment by Lorenzo45** [comment]
Hi @ctykaya - thanks for sharing the information. We are not able to reproduce the issue and have not received any other reports of this issue so it may be specific to your setup.

If you can reproduce the issue in our [Demo App](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/tree/master/DemoApp), please send us the modified project and we'll investigate.

One consideration is to check if you are using ProGuard or R8 to minify/obfuscate your code and if that is causing the issue.
