### ISSUE TITLE
A large number of crashes due to Yandex

### ISSUE THREAD

**Issue by MajidManzoor** [AppLovin/AppLovin-MAX-Unity-Plugin#415]
### MAX Plugin Version

12.6.0

### Unity Version

2022.3.33f1

### Device/Platform Info

All android devices

### Current Behavior

we are getting crash on android devices after yandex updated to v7.3.0.0.
Caused by java.lang.NoSuchMethodError: No static method -$$Nest$md(Lcom/yandex/mobile/ads/impl/wr1;)V in class Lcom/yandex/mobile/ads/impl/wr1; or its super classes (declaration of 'com.yandex.mobile.ads.impl.wr1' appears in base.apk!classes5.dex)
       at com.yandex.mobile.ads.impl.wr1$b.$r8$lambda$B-fNWrxWq_9ULcVBezH_aHeH2Qg()
       at com.yandex.mobile.ads.impl.wr1$b$$ExternalSyntheticLambda0.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8348)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
<img width="638" alt="Screenshot 2024-08-20 at 9 11 29 AM" src="https://github.com/user-attachments/assets/ce999445-dc6b-4fd6-a7b3-83b5f44c7eea">

### How to Reproduce

Not able to produce it yet.

### Additional Info

<img width="497" alt="Screenshot 2024-08-20 at 9 07 04 AM" src="https://github.com/user-attachments/assets/971640c5-72ee-44a2-9812-283bcaa06891">

**Comment by NanaAmoah** [comment]
Hi @MajidManzoor, since this crash is coming from the Yandex SDK, could you report it to them with the details so they can investigate?
