### ISSUE TITLE
Errors [MediationAdapterManager] Failed to load: com.applovin.mediation.adapters.*

### ISSUE THREAD

**Issue by doomcha** [AppLovin/AppLovin-MAX-Unity-Plugin#43]
Hello, Developers!

First of all I would like to thank your team for the unity plugin and the ability to integrate and use AppLovin Max in Unity engine. :)

I Integrated the plugin in to my game and started to test in on Android. Everything works fine, BUT, I noticed a lot of errors this kind:
....

Error AppLovinSdk [MediationAdapterManager] Failed to load: com.applovin.mediation.adapters.OguryMediationAdapter
Error AppLovinSdk java.lang.ClassNotFoundException: com.applovin.mediation.adapters.OguryMediationAdapter 

...

And these errors appear for every mediation network I didn't use (didn't install through Integration Manager). There are no crashes of course, but this errors make me worry. Is there any way to get rid of them?

Thanks! 

There is an example of the error logs for one network (they are all the same for all other networks as well), and I replaced the path to my project on [blablabla]:

`
[MediationAdapterManager] Failed to load: com.applovin.mediation.adapters.OguryMediationAdapter
java.lang.ClassNotFoundException: com.applovin.mediation.adapters.OguryMediationAdapter
	at java.lang.Class.classForName(Native Method)
 	at java.lang.Class.forName(Class.java:453)
 	at java.lang.Class.forName(Class.java:378)
 	at com.applovin.impl.mediation.i.a(Unknown Source:2)
 	at com.applovin.impl.mediation.i.a(Unknown Source:106)
 	at com.applovin.impl.mediation.h.a(Unknown Source:6)
 	at com.applovin.impl.mediation.b.a$1.run(Unknown Source:42)
 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.applovin.mediation.adapters.OguryMediationAdapter" on path: DexPathList[[zip file "[blablabla]/base.apk", zip file "[blablabla]/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[[blablabla]/lib/arm64, [blablabla]/base.apk!/lib/arm64-v8a, [blablabla]/split_config.arm64_v8a.apk!/lib/arm64-v8a, /system/lib64]]
 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 	... 13 more
 	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) [blablabla]/split_config.arm64_v8a.apk
 		at dalvik.system.DexFile.openDexFileNative(Native Method)
 		at dalvik.system.DexFile.openDexFile(DexFile.java:354)
 		at dalvik.system.DexFile.<init>(DexFile.java:101)
 		at dalvik.system.DexFile.<init>(DexFile.java:75)
 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
 		at dalvik.system.DexPathList.<init>(DexPathList.java:164)
 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
 		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:764)
 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:847)
 		at android.app.LoadedApk.getResources(LoadedApk.java:1088)
 		at android.app.ContextImpl.createAppContext(ContextImpl.java:2563)
 		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6149)
 		at android.app.ActivityThread.access$1200(ActivityThread.java:238)
 		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
 		at android.os.Handler.dispatchMessage(Handler.java:106)
 		at android.os.Looper.loop(Looper.java:214)
 		at android.app.ActivityThread.main(ActivityThread.java:7099)
 		at java.lang.reflect.Method.invoke(Native Method)
 		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
 		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
...
`

**Comment by thomasmso** [comment]
Hi, thanks for bringing this up. These are logs primarily for the AppLovin team so feel free to ignore them.

**Comment by doomcha** [comment]
> 
> 
> Hi, thanks for bringing this up. These are logs primarily for the AppLovin team so feel free to ignore them.

OK, I'll ignore them. Thank you a lot for your answer. :)
