### ISSUE TITLE
Too many crash on Crashlytics in one night

### ISSUE THREAD

**Issue by archengineer** [AppLovin/AppLovin-MAX-Unity-Plugin#44]
Hi,

We have started to see too much crash on our app and almost 8000 user effected from this in one night. This crash occurs both in interstitial and rewarded video ads.

Crashlog: 

Caused by java.lang.RuntimeException: Unable to start activity ComponentInfo{com.loop.match3d/com.applovin.adview.AppLovinInterstitialActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3162)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3305)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1993)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7285)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by thomasmso** [comment]
Hi @archengineer - The crash should have been resolved as of UTC 0, can you check your crash reporting to see if it is still occurring at a high frequency?

**Comment by archengineer** [comment]
Hi @thomasmso,

It seems this crash not occuring anymore, last occurrence 3 hours ago.
Thanks.
