### ISSUE TITLE
Steadly increse in ANR across the board on all our games (onDraw)

### ISSUE THREAD

**Issue by Mecze** [AppLovin/AppLovin-MAX-Unity-Plugin#451]
### MAX Plugin Version

6.5.2

### Unity Version

2022.3.8f1

### Device/Platform Info

Android. Across the board

### Crashes/ANRs per Day

around 10

### Percentage of Users Affected

1% of users for now

### First Occurrence of Crash/ANR

We are seeing an steady increase in ANR.
![image](https://github.com/user-attachments/assets/0061a987-0bf4-4c9e-846f-fd735a669a4d)
(last 30 days)

This new ANR seems to have started since around 09/09/2024
![image](https://github.com/user-attachments/assets/28e628a8-9dd9-4ac6-b1e7-6dfe8b37a1ec)
It happens in older versions of our app aswell of the latests ones (a seen in the image before)

![image](https://github.com/user-attachments/assets/67882b37-80a2-42fa-8bf7-63baf3f11829)

Also it is across all our games.

It does look suspiciously similar to the ANR provoked by Google's experimient on Web view that happened this summer.
https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/396

### Exception and Stack Trace

ANR triggered by slow operations in main thread

main (native):tid=1 systid=31053

#00 pc 0x4f66c [libc.so](http://libc.so/) (syscall + 28) (BuildId: 30a4e47a740c4b6340eb774cc965a471)
#01 pc 0x54060 [libc.so](http://libc.so/) (__futex_wait_ex + 144) (BuildId: 30a4e47a740c4b6340eb774cc965a471)
#02 pc 0xc113c [libc.so](http://libc.so/) (pthread_cond_wait + 76) (BuildId: 30a4e47a740c4b6340eb774cc965a471)
#03 pc 0x43bc674 base.apk + 4603904 (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#04 pc 0x43e84e0 base.apk + 4603904 (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#05 pc 0x4382310 base.apk + 4603904 (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#06 pc 0x465b4c0 base.apk + 4603904 (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#07 pc 0x35f2a24 base.apk + 4603904 (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#08 pc 0x4643e5c base.apk + 4603904 (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#09 pc 0x464dd90 base.apk + 4603904 (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#10 pc 0x46478d8 base.apk + 4603904 (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#11 pc 0x4647a18 base.apk + 4603904 (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#12 pc 0x46574ac base.apk + 4603904 (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#13 pc 0x2e28058 base.apk + 4603904 (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#14 pc 0x34d07b4 base.apk + 4603904 (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#15 pc 0x21bca68 base.apk + 4603904 (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#16 pc 0x218f17c base.apk (Java_J_N__1Z_1ZZIIIIIIJO + 68) (BuildId: 417cec9dda34587ccd57fb39777c686aae083caa)
#17 pc 0x378f70 [libart.so](http://libart.so/) (art_quick_generic_jni_trampoline + 144) (BuildId: 1ee2c234829500686eefa384068e67c8)
#18 pc 0x2123a0c memfd:jit-cache (WV.F6.onDraw + 1676)
#19 pc 0x21262d4 memfd:jit-cache (com.android.webview.chromium.WebViewChromium.onDraw + 308)
#20 pc 0x21c7e9c memfd:jit-cache (com.google.android.gms.ads.internal.webview.ai.onDraw + 220)
at J.N._Z_ZZIIIIIIJO(Native method)
at WV.F6.onDraw(chromium-TrichromeWebViewGoogle.aab-stable-672310731:289)
at com.android.webview.chromium.WebViewChromium.onDraw(chromium-TrichromeWebViewGoogle.aab-stable-672310731:40)
at android.webkit.WebView.onDraw(WebView.java:2930)
at com.google.android.gms.ads.internal.webview.ai.onDraw(:com.google.android.gms.policy_ads_fdr_dynamite@243799214@243799204017.685849251.685849251:8)
at android.view.View.draw(View.java:23341)
at android.view.View.draw(View.java:23207)
at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4350)
at android.view.View.draw(View.java:23205)
at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4350)
at android.view.View.draw(View.java:23205)
at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4350)
at android.view.View.draw(View.java:23205)
at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4350)
at android.view.View.draw(View.java:23205)
at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4350)
at android.view.View.draw(View.java:23348)
at android.view.View.draw(View.java:23207)
at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4350)
at android.view.View.draw(View.java:23205)
at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4350)
at android.view.View.draw(View.java:23205)
at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4350)
at android.view.View.draw(View.java:23205)
at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4350)
at android.view.View.draw(View.java:23348)
at com.android.internal.policy.DecorView.draw(DecorView.java:819)
at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:4852)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:4751)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4422)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3627)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2367)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9227)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1315)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1323)
at android.view.Choreographer.doCallbacks(Choreographer.java:956)
at android.view.Choreographer.doFrame(Choreographer.java:870)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1298)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7941)
at java.lang.reflect.Method.invoke(Native method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

### How to Reproduce

We see this in the Play Store Dev Console.

### Reproducible in the demo app?

Not Tested

**Comment by applovinAsh** [comment]
@Mecze, Several publishers have approached us regarding similar ANR increases that started at the beginning of September. While we are still investigating the issue, our initial findings suggest it is not specific to a single ad network but appears to be a widespread WebView-related issue similar to the one you linked.

**Comment by applovinAsh** [comment]
@Mecze, we are unsure of the root cause, but ANRs like these mainly come from a web view Chrome update on Google's side. We are investigating and will let you know when we have more information to share.

**Comment by alexXey62353** [comment]
Same here

**Comment by Mecze** [comment]
@applovinAsh we still having problems here... Did you find anything? 
Thanks!

**Comment by applovinAsh** [comment]
@Mecze, we are still investigating a solution, but as stated before, this is an issue with Google's Chrome Web Views, and the fix will ultimately need to come from Google.
