### ISSUE TITLE
collectGoogleAdvertisingInfo causes an error on android api < 26 (Android 7 and below)

### ISSUE THREAD

**Issue by eatsports** [AppLovin/AppLovin-MAX-Unity-Plugin#465]
### MAX Plugin Version

8.0.1

### Unity Version

2022.3.47

### Device/Platform Info

Devices with Android 7 or earlier

### Current Behavior

calling collectGoogleAdvertisingInfo results in calling java.time.Duration, which is not available on android 7
is it an issue with play-services-ads-identifier package or is it something you can fix?
here's a stacktrace:

          Caused by java.lang.ClassNotFoundException: Didn't find class "java.time.Duration" on path: DexPathList[[zip file "/data/app/com.tap.gallery-1/base.apk", zip file "/data/app/com.tap.gallery-1/split_UnityDataAssetPack.apk", zip file "/data/app/com.tap.gallery-1/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/com.tap.gallery-1/lib/arm64, /data/app/com.tap.gallery-1/base.apk!/lib/arm64-v8a, /data/app/com.tap.gallery-1/split_UnityDataAssetPack.apk!/lib/arm64-v8a, /data/app/com.tap.gallery-1/split_config.arm64_v8a.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.google.android.gms.ads.identifier.a.a(R8$$SyntheticClass:1)
       at com.google.android.gms.ads.identifier.zzd.<clinit>(com.google.android.gms:play-services-ads-identifier@@18.2.0:10)
       at com.google.android.gms.ads.identifier.zzd.zza(com.google.android.gms:play-services-ads-identifier@@18.2.0:1)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(com.google.android.gms:play-services-ads-identifier@@18.2.0:46)
       at com.applovin.impl.l0.collectGoogleAdvertisingInfo(SourceFile:19)
       at com.applovin.impl.l0.c(SourceFile:1)
       at com.applovin.impl.l0.a(SourceFile:9)
       at com.applovin.impl.l0.b(SourceFile:1)
       at com.applovin.impl.e5.b(SourceFile:1)
       at com.applovin.impl.e5.c(SourceFile:1)
       at com.applovin.impl.wu.run(R8$$SyntheticClass:3)
       at java.lang.Thread.run(Thread.java:762)

          Caused by java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
       at com.google.android.gms.ads.identifier.a.a(R8$$SyntheticClass:1)
       at com.google.android.gms.ads.identifier.zzd.<clinit>(com.google.android.gms:play-services-ads-identifier@@18.2.0:10)
       at com.google.android.gms.ads.identifier.zzd.zza(com.google.android.gms:play-services-ads-identifier@@18.2.0:1)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(com.google.android.gms:play-services-ads-identifier@@18.2.0:46)
       at com.applovin.impl.l0.collectGoogleAdvertisingInfo(SourceFile:19)
       at com.applovin.impl.l0.c(SourceFile:1)
       at com.applovin.impl.l0.a(SourceFile:9)
       at com.applovin.impl.l0.b(SourceFile:1)
       at com.applovin.impl.e5.b(SourceFile:1)
       at com.applovin.impl.e5.c(SourceFile:1)
       at com.applovin.impl.wu.run(R8$$SyntheticClass:3)
       at java.lang.Thread.run(Thread.java:762)

          Caused by java.lang.NoClassDefFoundError: com.google.android.gms.ads.identifier.zzd
       at com.google.android.gms.ads.identifier.zzd.zza(com.google.android.gms:play-services-ads-identifier@@18.2.0:1)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(com.google.android.gms:play-services-ads-identifier@@18.2.0:46)
       at com.fyber.inneractive.sdk.config.N.a(SourceFile:3)
       at com.fyber.inneractive.sdk.config.M.run(SourceFile:14)
       at java.lang.Thread.run(Thread.java:762)

### Expected Behavior

No errors when calling collectGoogleAdvertisingInfo

### How to Reproduce

call collectGoogleAdvertisingInfo on an Android 7 device

### Reproducible in the demo app?

Not Tested

**Comment by applovinAsh** [comment]
@eatsports - Please try enabling desugaring in your build.gradle file. For more information, see here: https://developer.android.com/studio/write/java8-support.
